Mejorando el primer caso de prueba
stevenasuarez/protractor-workshop-2017 pull request #2
Opened 2017-10-07 02:53 UTC by stevenasuarez

2017-10-07 12:45 UTC, aperdomob requested changes

2017-10-07 12:45 UTC, aperdomob commented on test/Google.spec.js
> +});
EOF

2017-10-07 12:45 UTC, aperdomob commented on test/Google.spec.js
> +
Eliminar espacio en blanco

2017-10-08 18:45 UTC, stevenasuarez commented on test/Google.spec.js
> +
Listo, ya corregido el espacio

2017-10-08 18:47 UTC, aperdomob requested changes

2017-10-08 18:47 UTC, aperdomob commented on test/Google.spec.js
> +});
Falta este EOF

2017-10-08 20:10 UTC, stevenasuarez commented on test/Google.spec.js
> +});
Corregido, perdón tanto EOF

2017-10-08 21:13 UTC, aperdomob requested changes

2017-10-08 21:13 UTC, aperdomob commented on test/Google.spec.js
> +  });
EOF

2017-10-08 21:25 UTC, stevenasuarez commented on test/Google.spec.js
> +  });
Se añade el espacio al final del documento

2017-10-08 21:45 UTC, aperdomob approved these changes

2017-10-08 22:49 UTC, merged